export type Attributes = {
  lat: number,
  lng: number,
  zoom: number,
  bearing: number,
  pitch: number,
  hash: 'on' | 'off',
  marker: 'on' | 'off',
  markerColor: string,
  openPopup: 'on' | 'off',
  customMarker: string,
  customMarkerOffset: string,
  gestureHandling: 'on' | 'off',
  navigationControl: 'on' | 'off',
  geolocateControl: 'on' | 'off',
  fullscreenControl: 'on' | 'off',
  scaleControl: 'on' | 'off',
  geoloniaControl: 'on' | 'off',
  geojson: string,
  simpleVector: string,
  cluster: 'on' | 'off',
  clusterColor: string,
  style: string,
  lang: string,
  plugin: 'on' | 'off',
  key: string,
  apiUrl: string,
  stage: string,
  loader: 'on' | 'off',
  minZoom: number | '',
  maxZoom: number,
  '3d': string,
};
